# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RatfQgisDialog
                                 A QGIS plugin
 Validation géométrique RATF pour QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-14
        git sha              : $Format:%H$
        copyright            : (C) 2026 by JFB
        email                : jessicaf.bolduc@horizon-sf.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import (QListWidgetItem, QMessageBox, QProgressDialog, QApplication)

from qgis.core import (QgsProject, QgsWkbTypes, QgsMapLayer)

import geometry as gp

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'ratf_qgis_dialog_base.ui'),
    from_imports=True,
    import_from='ratf_qgis')


class RatfQgisDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(RatfQgisDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Charger les couches polygonales
        self.load_polygon_layers()

        # Connexion des signaux
        self.lstPolygonLayers.itemChanged.connect(self.on_layer_checked)
        self.btnExecute.clicked.connect(self.on_execute_clicked)
        self.btnClose.clicked.connect(self.close)

    def load_polygon_layers(self):
        """Charge toutes les couches polygonales du projet dans la liste."""

        # Vider la liste
        self.lstPolygonLayers.clear()

        # Parcourir toutes les couches du projet
        for layer in QgsProject.instance().mapLayers().values():

            # Vérifier que c'est une couche vecteur polygonale
            if layer.type() == QgsMapLayer.VectorLayer and \
                    layer.geometryType() == QgsWkbTypes.PolygonGeometry:
                
                item = QListWidgetItem(layer.name())                                       
                item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
                item.setCheckState(Qt.Unchecked)
                # Sauvegarder directement la couche
                item.setData(Qt.UserRole, layer)
                self.lstPolygonLayers.addItem(item)

    def on_layer_checked(self, current_item):
        """Permet une seule couche sélectionnée à la fois."""

        if current_item.checkState() != Qt.Checked:
            return
        
        self.lstPolygonLayers.blockSignals(True)
        for i in range(self.lstPolygonLayers.count()):
            item = self.lstPolygonLayers.item(i)

            if item != current_item:
                item.setCheckState(Qt.Unchecked)

        self.lstPolygonLayers.blockSignals(False)

    def selected_layer(self):
        """Retourne la couche actuellement sélectionnée (ou None)."""

        for i in range(self.lstPolygonLayers.count()):
            item = self.lstPolygonLayers.item(i)

            if item.checkState() == Qt.Checked:
                return item.data(Qt.UserRole)
            
        return None
    
    # -------------------------------------------------------------
    # Exécution des traitements
    # -------------------------------------------------------------
    def on_execute_clicked(self):
        layer = self.selected_layer()
        if layer is None:
            QMessageBox.warning(
                self, "Géométrie RATF",
                "Aucune couche sélectionnée.")
            return
        
        min_area_ha = self.spinSuperficieMin.value()

        progress = QProgressDialog(
            f"Traitement de la couche « {layer.name()} »...", "Annuler", 0, 5, self)
        progress.setWindowModality(Qt.WindowModal)
        progress.show()

        rapport = [f"--- Couche : {layer.name()} ---"]
        step = 0

        # Anomalies normalisées de tous les contrôles "Détecter / Montrer",
        # accumulées ici pour être affichées dans une seule couche à la fin.
        anomalies_detectees = []

        # 1. Distance minimale entre les sommets
        if self.chkVerifyMinVertex.isChecked() or self.chkCorrectMinVertex.isChecked():
            val = self.spnMinVertexDistance.value()

            if self.chkVerifyMinVertex.isChecked():
                issues = gp.check_min_vertex_distance(layer, val, min_area_ha)
                rapport.append(f"  Distance min. entre sommets : {len(issues)} anomalie(s) détectée(s)")

                if issues:
                    anomalies_detectees.extend(gp.normalize_issues(
                        issues, "Distance min. entre sommets, value_key="distance,
                        fid_key="fid", value_suffix=" m"))
                    
            if self.chkCorrectMinVertex.isChecked():
                n = gp.correct_min_vertex_distance(layer, val, min_area_ha)
                rapport.append(f"  Distance min. entre sommets : {n} entit(s) corrigée(s)")
        step += 1
        progress.setValue(step)
        QApplication.processEvents()
        if progress.wasCanceled():
            return
        
        # 2. Distance maximale entre les sommets
        if self.chkVerifyMaxVertex.isChecked() or self.chkCorrectMaxVertex.isChecked():
            val = self.spnMaxVertexDistance.value()

            if self.chkVerifyMaxVertex.isChecked():
                issues = gp.check_max_vertex_distance(layer, val, min_area_ha)
                rapport.append(f"  Distance max. entre sommets : {len(issues)} anomalie(s) détectée(s)")

                if issues:
                    anomalies_detectees.extend(gp.normalize_issues(
                        issues, "Distance max. entre sommets", value_key="distance",
                        fid_key="fid", value_suffix=" m"))

            if self.chkCorrectMaxVertex.isChecked():
                n = gp.correct_max_vertex_distance(layer, val, min_area_ha)
                rapport.append(f"  Distance max. entre sommets : {n} entité(s) corrigée(s)")
        step +=1
        progress.setValue(step)
        QApplication.proccesEvents()
        if progress.wasCanceled():
            return
        
        # 3. Proximité des segments intra-géométrie
        if self.chkDetectSegIntra.isChecked():
            val = self.spnSegmentsIntra.value()
            issues = gp.check_intra_geometry_proximity(layer, val, min_area_ha)
            rapport.append(f"  Proximité intra-géométrie : {len(issues)} anomalie(s) détectée(s)")

            if self.chkShowSegIntra.isChecked() and issues:
                anomalies_detectees.extend(gp.normalize_issues(
                    issues, "Proximité intra-géométrie", value_key="distance",
                    fid_key="fid", value_suffix=" m"))
        
        step +=1
        progress.setValue(step)
        QApplication.processEvents()
        if progress.wasCanceled():
            return
        
        # 4. Proximité des segments inter-géométrie
        if self.chkDetectSehInter.isChecked():
            val = self.spnSegmentsInter.value()
            issues = gp.check_inter_geometry_proximity(layer, val, min_area_ha)
            rapport.append(f"  Proximité inter-géométrie : {len(issues)} anomalie(s) détectée(s)")

            if self.chkShowSegInter.isChecked() and issues:
                anomalies_detectees.extend(gp.normalize_issues(
                    issues, "Proximité inter-géométrie", value_key="distance",
                    fid_key="fid_a", fid_b_key="fid_b", value_suffix=" m"
                ))
        step +=1
        progress.setValue(step)
        QApplication.processEvents()
        if progress.wasCanceled():
            return
        
        # 5. Angles internes de bordures
        if self.chkDetectAnglesInternes.isChecked():
            val = self.spnAnglesInternes.value()
            issues = gp.check_internal_angles(layer, val, min_area_ha)
            rapport.append(f"  Angles interne < {val}° : {len(issues)} anomalie(s) détectée(s)")

            if self.chkShowAngles.isChecked() and issues:
                anomalies_detectees.extend(gp.normalize_issues(
                    issues, "Angles interne", value_key="angle",
                    fid_key="fid", value_suffix="°"
                ))
        step +=1
        progress.setValues(step)

        # Couche unique regroupant toutes les anomalies, distinguées par le champ "type".
        if anomalies_detectees:
            couche_erreurs = gp.build_combined_point_layer(
                anomalies_detectees, layer.crs(), f"{layer_name()}_erreurs_detectees")
            
            if couche_erreurs is not None:
                QgsProject.instance().addMapLayer(couche_erreurs)
                rapport.append(
                    f"\n {len(anomalies_detectees)} anomalie(s) affichée(s) dans la couche"
                    f"« {couche_erreurs.name()} »")
                
        layer.triggerRepaint()

        QMessageBox.information(self, "Géométrie RATF - Rapport", "\n".join(rapport))

